blogster/urls.py
# BLOGSTER by Alexander Abraham
# a.k.a. "The Black Unicorn" a.k.a. "Angeldust Duke".
# Licensed under the MIT license.

from django.urls import path
from django.urls import include
from django.contrib import admin
urlpatterns = [
    path('god', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
# BLOGSTER by Alexander Abraham
# a.k.a. "The Black Unicorn" a.k.a. "Angeldust Duke".
# Licensed under the MIT license.

from . import views
from django.urls import path
app_name = 'posts'
urlpatterns = [
    path('', views.blog, name='blog'),
    path('api/posts', views.api, name='api'),
    path('<str:title>', views.post, name='post'),
    path('api/site', views.settings_api, name='site_api')
]

posts/models.py
# BLOGSTER by Alexander Abraham
# a.k.a. "The Black Unicorn" a.k.a. "Angeldust Duke".
# Licensed under the MIT license.

from django.db import models

class Post(models.Model):
    """
    A post with the fields below.
    """
    title = models.CharField(max_length=2000)
    description = models.CharField(max_length=20000)
    body = models.TextField(max_length=200000)
    date = models.DateTimeField(verbose_name='date',auto_now=True)
    def __str__(self):
        return self.title

posts/views.py
# BLOGSTER by Alexander Abraham
# a.k.a. "The Black Unicorn" a.k.a. "Angeldust Duke".
# Licensed under the MIT license.

from .models import Post
from django.conf import settings
from django.shortcuts import render
from django.http import JsonResponse

def blog(request):
    """
    Fetches all post objects
    and returns the [posts/blog.html]
    template with an iterator for context.
    """
    all_posts = Post.objects.all()
    context = {
        'posts':all_posts
    }
    context.update(settings.SITE_VARS)
    return render(
        request,
        'posts/blog.html',
        context
    )

def post(request, title):
    """
    Fetches a post object by title
    and returns the [posts/post.html]
    template with all post data for context.
    """
    post = Post.objects.get(title=title)
    post_body = post.body
    post_date = post.date
    post_description = post.description
    context = {
        'title':title,
        'body':post_body,
        'date':post_date,
        'description':post_description
    }
    context.update(settings.SITE_VARS)
    return render(
        request,
        'posts/post.html',
        context
    )

def settings_api(request):
    """
    We return a [JsonResponse]
    of global site variables, if desired.
    """
    return JsonResponse(settings.SITE_VARS, safe=False)

def api(request):
    """
    Fetches all post objects,
    serializes them in a dictinary,
    and returns a [JsonResponse].
    """
    all_posts = Post.objects.all()
    result = {}
    for post in all_posts:
        body = post.body
        date = post.date
        title = post.title
        description = post.description
        result[title] = [
            description,
            body,
            date
        ]
    return JsonResponse(result, safe=False)

templates/posts/blog.html
<!DOCTYPE html>
<html>

<head>
 <meta charset="UTF-8"/>
 <title>{{ site_name }}</title>
 <meta name="keywords" content="{{ site_keywords }}"/>
 <meta name="robots" content="{{ site_description }}"/>
 <meta name="msapplication-TileColor" content="#000000">
 <meta name="description" content="{{ site_description }}"/>
 <link rel="apple-touch-icon" sizes="57x57" href="{{ site_57x57_icon }}">
 <link rel="apple-touch-icon" sizes="60x60" href="{{ site_60x60_icon }}">
 <link rel="apple-touch-icon" sizes="72x72" href="{{ site_72x72_icon }}">
 <link rel="apple-touch-icon" sizes="76x76" href="{{ site_76x76_icon }}">
 <link rel="apple-touch-icon" sizes="114x114" href="{{ site_114x114_icon }}">
 <link rel="apple-touch-icon" sizes="120x120" href="{{ site_120x120_icon }}">
 <link rel="apple-touch-icon" sizes="144x144" href="{{ site_144x144_icon }}">
 <link rel="apple-touch-icon" sizes="152x152" href="{{ site_152x152_icon }}">
 <link rel="apple-touch-icon" sizes="180x180" href="{{ site_180x180_icon }}">
 <link rel="icon" type="image/png" sizes="192x192"  href="{{ site_192x192_icon }}">
 <link rel="icon" type="image/png" sizes="32x32" href="{{ site_32x32_icon }}">
 <link rel="icon" type="image/png" sizes="96x96" href="{{ site_96x96_icon }}">
 <link rel="icon" type="image/png" sizes="16x16" href="{{ site_16x16_icon }}">
 <meta name="msapplication-TileImage" content="{{ site_144x144_icon }}">
 <meta name="twitter:card" content="summary_large_image">
 <meta name="twitter:image:alt" content="{{ site_banner_description }}">
 <meta name="twitter:title" content="{{ site_name }}">
 <meta name="twitter:description" content="{{ site_description }}">
 <meta property="og:image" content="{{ site_social_banner }}">
 <meta name="twitter:image" content="{{ site_social_banner }}">
 <meta property="og:image:type" content="image/png">
 <meta name="viewport" content="width=device-width, initial-scale=1"/>
 <link rel="stylesheet" type="text/css" href="{{ site_css }}"/>
</head>

 <body>
   <img class="profile_pic" src="{{ site_pic }}"/>
   <h1>{{ site_name }}</h1>

  {% if posts %}

   {% for post in posts %}
    <div class="content">
     <h2>{{ post.title }}</h2>
     <p>
      {{ post.description }}
     </p>
     <hr class="divider"/>
     <p>
      <a href="{% url 'posts:post' title=post.title %}">Read</a>
     </p>
    </div>
   {% endfor %}

  {% else %}

   <div class="content">
    <h2>No posts yet!</h2>
    <p>
     No posts here yet! Stay tuned!
    </p>
   </div>

  {% endif %}

 </body>

</html>

templates/posts/post.html
<!DOCTYPE html>
<html>

 <head>
  <meta charset="UTF-8"/>
  <title>{{ site_name }}</title>
  <meta name="keywords" content="{{ site_keywords }}"/>
  <meta name="robots" content="{{ site_description }}"/>
  <meta name="msapplication-TileColor" content="#000000">
  <meta name="description" content="{{ site_description }}"/>
  <link rel="apple-touch-icon" sizes="57x57" href="{{ site_57x57_icon }}">
  <link rel="apple-touch-icon" sizes="60x60" href="{{ site_60x60_icon }}">
  <link rel="apple-touch-icon" sizes="72x72" href="{{ site_72x72_icon }}">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ site_76x76_icon }}">
  <link rel="apple-touch-icon" sizes="114x114" href="{{ site_114x114_icon }}">
  <link rel="apple-touch-icon" sizes="120x120" href="{{ site_120x120_icon }}">
  <link rel="apple-touch-icon" sizes="144x144" href="{{ site_144x144_icon }}">
  <link rel="apple-touch-icon" sizes="152x152" href="{{ site_152x152_icon }}">
  <link rel="apple-touch-icon" sizes="180x180" href="{{ site_180x180_icon }}">
  <link rel="icon" type="image/png" sizes="192x192"  href="{{ site_192x192_icon }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ site_32x32_icon }}">
  <link rel="icon" type="image/png" sizes="96x96" href="{{ site_96x96_icon }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ site_16x16_icon }}">
  <meta name="msapplication-TileImage" content="{{ site_144x144_icon }}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:image:alt" content="{{ site_banner_description }}">
  <meta name="twitter:title" content="{{ site_name }}">
  <meta name="twitter:description" content="{{ site_description }}">
  <meta property="og:image" content="{{ site_social_banner }}">
  <meta name="twitter:image" content="{{ site_social_banner }}">
  <meta property="og:image:type" content="image/png">
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" type="text/css" href="{{ site_css }}"/>
 </head>

 <body>
  <img class="profile_pic" src="{{ site_pic }}"/>
  <h1>{{ site_name }}</h1>

  <div class="content">
   <h2>{{ title }}</h2>
   <p>
    {{ description }}
   </p>
   <p>
    {{ date }}
   </p>
   <p>
    {{ body }}
   </p>
  </div>
 </body>

</html>